### ISSUE TITLE
Discrepancy in Z Value Range Causing Curve Misalignment

### ISSUE THREAD

**Issue by asdqwfgg** [Hamza-Kamil/Transfer-Learning-PINN-Nitrogen#1]
Dear Professor,

In the code you provided, the value of Z ranges from 0 to 1, while in the actual data, Z ranges from 0 to -1. This discrepancy in standards appears to cause a misalignment in the resulting image. Although the trend of the curve remains consistent, there is a noticeable shift in its position. I’m uncertain whether this issue arises from a misunderstanding on my part regarding the code or the article. Any clarification you could provide would be greatly appreciated.
![微信图片_20241110190022](https://github.com/user-attachments/assets/f4b04834-81a0-4aee-abe9-d020236f0590)

**Comment by Hamza-Kamil** [comment]
Hello,

Thank you for your observation.

The choice of soil domain coordinates (whether 0 to -1 or 0 to 1) is purely conventional and doesn't affect the underlying physics, as long as we properly account for the flow direction. In HYDRUS-1D, the convention places the soil surface at z=0 with negative values extending downward (0 to -1).

To directly address your visualization issue: The apparent misalignment you're seeing is simply due to different coordinate conventions. To resolve this, you should plot both the HYDRUS and PINN solutions using the same z-coordinate system. You can either:
- Transform the PINN results to match HYDRUS's 0 to -1 convention, or
- Transform the HYDRUS results to match your 0 to 1 system

This will align your curves properly while preserving all physical relationships.

Best regards,
Hamza Kamil
________________________________
From: asdqwfgg ***@***.***>
Sent: Sunday, November 10, 2024 12:03
To: Hamza-Kamil/Transfer-Learning-PINN-Nitrogen ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Hamza-Kamil/Transfer-Learning-PINN-Nitrogen] Discrepancy in Z Value Range Causing Curve Misalignment (Issue #1)

[ATTENTION : Ce courriel provient de l'extérieur de l'ÉTS]
Évitez de cliquer sur un lien ou d'ouvrir une pièce jointe si vous ne connaissez pas l'expéditeur du courriel. En cas de doute, veuillez SVP créer un billet Problème de courriel au GUS<https://gus.etsmtl.ca/c2atom/LoginAzure?landingPage=/portal-request-form/714d9e14-bc17-47b8-a0e6-e154184ecbc2> .



Dear Professor,

In the code you provided, the value of Z ranges from 0 to 1, while in the actual data, Z ranges from 0 to -1. This discrepancy in standards appears to cause a misalignment in the resulting image. Although the trend of the curve remains consistent, there is a noticeable shift in its position. I’m uncertain whether this issue arises from a misunderstanding on my part regarding the code or the article. Any clarification you could provide would be greatly appreciated.
_20241110190022.png (view on web)<https://github.com/user-attachments/assets/f4b04834-81a0-4aee-abe9-d020236f0590>

**Comment by asdqwfgg** [comment]
Dear Professor Kamil,

Thank you very much for your prompt and detailed response. I appreciate your explanation regarding the coordinate conventions and the clarification on how this affects the visualization. I now have a better understanding of the issue.

I will adjust the coordinate system accordingly and ensure that both the HYDRUS and PINN solutions are plotted with consistent conventions to resolve the misalignment.

Thanks again for your guidance.

Best regards
